### PR TITLE
move kepler dependencies from _installCI to _installUbuntuPackages

### LINKED ISSUE #3968: Issue with installation - cmake can't find "FindTBB.cmake" configuration file
### Subject

[Build] for compilation-related issues.

### Describe the bug

Good day! I'm trying to build OpenROAD Flow Scripts in a fresh Ubuntu 24 setup using the instructions from [the documentation](https://openroad-flow-scripts.readthedocs.io/en/latest/user/BuildLocally.html) and I'm getting the following error at the end of the `./build_openroad.sh --local` step:

```
CMake Error at thirdparty/naja/CMakeLists.txt:102 (find_package):
  By not providing "FindTBB.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "TBB", but
  CMake did not find one.

  Could not find a package configuration file provided by "TBB" with any of
  the following names:

    TBBConfig.cmake
    tbb-config.cmake

  Add the installation prefix of "TBB" to CMAKE_PREFIX_PATH or set "TBB_DIR"
  to a directory containing one of the above files.  If "TBB" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
```
There are some CMake warnings between lines 60 - 93 about some library conflicts too, if this is relevant.

I hope this is a solved problem! I opened the issue due to not finding anything in the issues. Thank you for your help!

### Expected Behavior

I expected the configuration to go through, since this is a fresh setup without any other software other than the basics that Ubuntu 24.04 comes with and ORFS's dependencies.

### Environment

```shell
The Env.sh file is missing in ~/OpenROAD-flow-scripts/etc/
```

### To Reproduce

On the fresh build: 
- Installed `git` and `npm` for the software, then `CMake` for the dependencies
- Used `npm` to install `bazelisk` via `npm install -g @bazel/bazelisk` according to [this documentation](https://github.com/bazelbuild/bazelisk) then ran `bazelisk` once for it to install `bazel`.
Then I used the steps in the documentation:
```Bash
git clone --recursive https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts
cd OpenROAD-flow-scripts
sudo ./setup.sh
cd tools/OpenROAD
bazelisk test src/drt/...
cd ../../flow
make OPENROAD_EXE=$(pwd)/../tools/OpenROAD/bazel-out/k8-opt-exec-ST-*/bin/openroad
./build_openroad.sh --local
```

### Relevant log output

```shell
[INFO FLW-0002] Updating git submodules.
[INFO FLW-0001] Using local build method. This will create binaries at 'tools/install' unless overwritten.
[INFO FLW-0018] Compiling OpenROAD.
[INFO] Using additional CMake parameters from /home/themi/OpenROAD-flow-scripts/tools/OpenROAD/etc/openroad_deps_prefixes.txt
[INFO] Saving logs to /home/themi/OpenROAD-flow-scripts/tools/OpenROAD/build/openroad_build.log
[INFO] ./tools/OpenROAD/etc/Build.sh -dir=/home/themi/OpenROAD-flow-scripts/tools/OpenROAD/build -threads=8 -cmake= -D CMAKE_INSTALL_PREFIX=/home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD -D CMAKE_INSTALL_RPATH=/home/themi/OpenROAD-flow-scripts/dependencies/lib:/home/themi/OpenROAD-flow-scripts/dependencies/lib64 -D CMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE 
[INFO] Using 8 threads.
-- OpenROAD version: 26Q1-1744-g138e57370c
-- System name: Linux
-- Compiler: GNU 13.3.0
-- Build type: RELEASE
-- Install prefix: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD
-- C++ Standard: 20
-- C++ Standard Required: ON
-- C++ Extensions: OFF
-- LTO/IPO is enabled
-- Performing Test C_COMPILER_SUPPORTS__-std=c++17
-- Performing Test C_COMPILER_SUPPORTS__-std=c++17 - Failed
-- Performing Test CXX_COMPILER_SUPPORTS__-std=c++17
-- Performing Test CXX_COMPILER_SUPPORTS__-std=c++17 - Success
-- TCL library: /usr/lib/x86_64-linux-gnu/libtcl.so
-- TCL header: /usr/include/tcl/tcl.h
-- TCL readline library: /usr/lib/x86_64-linux-gnu/libtclreadline.so
-- TCL readline header: /usr/include/x86_64-linux-gnu
-- Found SWIG: /home/themi/OpenROAD-flow-scripts/dependencies/bin/swig (found suitable version "4.3.0", minimum required is "4.0")
-- Using SWIG >= 4.3.0 -flatstaticmethod flag for python
-- boost: 1.89.0
-- absl: 20260107
-- GTest: 1.17.0
-- spdlog: 1.15.0
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- STA version: 3.0.0
-- STA git sha: 16ac05c87a2a7f4a85dca8ae571beab7879bb09b
-- System name: Linux
-- Compiler: GNU 13.3.0
-- Build type: RELEASE
-- Build CXX_FLAGS: -O3 -DNDEBUG
-- Install prefix: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD
-- IPO/LTO: not supported - CMake doesn't support IPO for current C compiler
-- TCL library: /usr/lib/x86_64-linux-gnu/libtcl.so
-- TCL header: /usr/include/tcl/tcl.h
-- TCL readline library: /usr/lib/x86_64-linux-gnu/libtclreadline.so
-- TCL readline header: /usr/include/x86_64-linux-gnu/tclreadline.h
-- CUDD library: /home/themi/OpenROAD-flow-scripts/dependencies/lib/libcudd.a
-- CUDD header: /home/themi/OpenROAD-flow-scripts/dependencies/include/cudd.h
-- SSTA: 0
-- Found SWIG: /home/themi/OpenROAD-flow-scripts/dependencies/bin/swig (found suitable version "4.3.0", minimum required is "3.0")
-- STA library: /home/themi/OpenROAD-flow-scripts/tools/OpenROAD/build/libOpenSTA.a
-- STA executable: /home/themi/OpenROAD-flow-scripts/tools/OpenROAD/build/sta
-- Found OR-Tools: /home/themi/OpenROAD-flow-scripts/dependencies/lib/cmake/ortools (version: 9.14.6206)
-- TCL library: /usr/lib/x86_64-linux-gnu/libtcl.so
-- TCL header: /usr/include/tcl/tcl.h
-- Found OpenMP: TRUE (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- GUI is enabled
-- Could NOT find VTune (missing: VTune_LIBRARIES VTune_INCLUDE_DIRS) 
-- TCL library: /usr/lib/x86_64-linux-gnu/libtcl.so
-- TCL header: /usr/include/tcl/tcl.h
-- TCL readline enabled
-- Tcl Extended disabled
-- Python3 enabled
-- Configuring done (2.3s)
CMake Warning at src/CMakeLists.txt:294 (add_executable):
  Cannot generate a safe runtime search path for target openroad because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/themi/OpenROAD-flow-scripts/dependencies/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/gpl/test/CMakeLists.txt:67 (add_executable):
  Cannot generate a safe runtime search path for target mbff_test because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/themi/OpenROAD-flow-scripts/dependencies/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/mpl/test/cpp/CMakeLists.txt:15 (add_executable):
  Cannot generate a safe runtime search path for target TestSnapper because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/themi/OpenROAD-flow-scripts/dependencies/lib

  Some of these libraries may not be found correctly.


-- Generating done (1.4s)
-- Build files have been written to: /home/themi/OpenROAD-flow-scripts/tools/OpenROAD/build
[  0%] Built target gui_RUNTIME_HEADER
[  1%] Built target defzlib
[  1%] Built target Munkres
[  1%] Built target lefzlib
[  1%] Built target sta_swig_swig_compilation
[  1%] Generating messages.checked
[  1%] Built target fft_test
[  2%] Built target utl_py
[  2%] Built target lef
[  4%] Built target def
[  4%] Built target utl_lib
[  4%] Generating messages.checked
[  4%] Built target TestMetrics
[  4%] Built target TestCFileUtils
[  4%] Built target TestAlgorithms
[  5%] Built target TestSuppressStdout
[  7%] Built target zutil
[  7%] Built target ppl_messages
[  7%] Built target utl_messages
[  7%] Built target dst_lib
[  7%] Generating messages.checked
[  7%] Built target utl
[  7%] Built target dst_messages
[  7%] Built target dst
[  7%] Built target TestBalancer
[  8%] Built target TestDistributed
[  8%] Built target TestWorker
[ 14%] Built target OpenSTA
[ 14%] Generating messages.checked
[ 16%] Built target sta_swig
[ 16%] Built target sta
[ 16%] Built target openroad_messages
[ 23%] Built target db
[ 23%] Built target gdsout
[ 23%] Built target lefout
[ 23%] Built target cdl
[ 23%] Built target defout
[ 23%] Built target gdsin
[ 23%] Built target 3dblox
[ 23%] Built target defin
[ 73%] Built target libabc
[ 73%] Built target abc
[ 74%] Built target lefin
[ 74%] Generating messages.checked
[ 74%] Built target odb_swig_common
[ 74%] Built target odb_messages
[ 74%] Built target gui_autogen_timestamp_deps
[ 74%] Built target exa_lib
[ 76%] Built target odbtcl
[ 76%] Built target odb_py
[ 76%] Built target stt_lib
[ 76%] Built target ant_lib
[ 76%] Built target dft_config_lib
[ 76%] Built target dft_utils_scan_pin_lib
[ 76%] Built target odb_py-bin
[ 76%] Built target odbtcl-bin
[ 76%] Generating messages.checked
[ 76%] Built target dbSta_lib
[ 76%] Generating messages.checked
[ 76%] Generating messages.checked
[ 76%] Built target gui_autogen
[ 76%] Built target exa_messages
[ 76%] Built target tap
[ 76%] Built target stt_messages
[ 76%] Built target dft_clock_domain_lib
[ 76%] Generating messages.checked
[ 76%] Built target ant_messages
[ 76%] Built target tap_py
[ 76%] Built target CUGR
[ 76%] Built target dft_clock_domain_hash_lib
[ 76%] Built target dbSta_messages
[ 77%] Built target par_lib
[ 77%] Built target dft_base_scan_cell_lib
[ 77%] Built target par_py
[ 77%] Built target par
[ 77%] Built target dbSta
[ 77%] Built target ord
[ 77%] Built target upf_lib
[ 77%] Built target dft_utils_lib
[ 79%] Built target rcx_lib
[ 79%] Built target dft_architect_lib
[ 79%] Built target ifp
[ 80%] Built target upf
[ 80%] Built target mpl_lib
[ 80%] Built target rcxUnitTest
[ 80%] Built target dft_replace_lib
[ 80%] Built target dft_cells_lib
[ 80%] Generating messages.checked
[ 80%] Built target TestScanArchitect
[ 80%] Built target TestScanArchitectHeuristic
[ 80%] Built target ord_py
[ 80%] Built target ifp_py
[ 80%] Built target rcx_py
[ 80%] Built target dft_stitch_lib
[ 80%] Generating messages.checked
[ 80%] Built target dft_messages
[ 80%] Built target rcx_messages
[ 80%] Built target dft
[ 80%] Built target rcx
[ 80%] Built target dft_py
[ 80%] Built target dpl_lib
[ 80%] Generating messages.checked
[ 82%] Built target gui
[ 82%] Built target est_lib
[ 82%] Built target exa_py
[ 83%] Built target exa
[ 83%] Built target stt
[ 83%] Built target fin
[ 83%] Built target dpl_messages
[ 85%] Built target dpl_py
[ 85%] Built target mpl
[ 85%] Built target stt_py
[ 85%] Built target fin_py
[ 85%] Built target ppl
[ 85%] Built target FastRoute4.1
[ 85%] Built target ppl_py
[ 86%] Built target dpl
[ 86%] Built target pad
[ 86%] Built target grt_lib
[ 86%] Built target pdn
[ 88%] Built target pdn_py
[ 88%] Built target rsz_lib
[ 88%] Generating messages.checked
[ 89%] Generating messages.checked
[ 89%] Generating messages.checked
[ 89%] Built target est_messages
[ 89%] Built target ant
[ 89%] Built target grt_messages
[ 89%] Built target cut
[ 89%] Built target rsz_messages
[ 89%] Built target tst
[ 89%] Built target gpl_lib
[ 89%] Built target odb_test_helper
[ 89%] Built target cts_lib
[ 89%] Built target est
[ 89%] Built target TestHconn
[ 89%] Built target cgt
[ 89%] Built target psm
[ 89%] Built target TestDbSta
[ 89%] Built target TestReadVerilog
[ 89%] Built target TestBufRem1
[ 89%] Built target TestBufferRemoval2
[ 89%] Built target TestBufferRemoval3
[ 89%] Built target TestInsertBuffer
[ 89%] Built target dpl_test
[ 89%] Built target TestSnapper
[ 89%] Built target mbff_test
[ 89%] Built target cts_unittest
[ 89%] Built target CutGTests
[ 89%] Generating messages.checked
[ 91%] Built target cgt_py
[ 92%] Built target psm_py
[ 92%] Built target TestCallBacks
[ 92%] Built target TestGeom
[ 92%] Built target grt
[ 94%] Built target OdbGTests
[ 97%] Built target drt_lib
[ 97%] Built target TestModule
[ 98%] Built target rmp_lib
[ 98%] Built target TestLef58Properties
[ 98%] Built target TestGroup
[ 98%] Built target TestJournal
[ 98%] Built target TestAccessPoint
[ 98%] Built target TestGuide
[ 98%] Built target TestNetTrack
[ 98%] Built target TestGCellGrid
[ 98%] Built target cts_messages
[ 98%] Built target TestMaster
[ 98%] Built target TestGDSIn
[ 98%] Built target TestChips
[ 98%] Built target Test3DBloxParser
[ 98%] Built target TestSwapMaster
[ 98%] Built target Test3DBloxChecker
[ 98%] Built target TestSwapMasterUnusedPort
[ 98%] Generating messages.checked
[ 98%] Built target TestScanChain
[ 98%] Built target TestObjectType
[ 98%] Built target grt_py
[ 98%] Built target TestWriteReadDbHier
[ 98%] Built target trTest
[ 98%] Built target RmpGTests
[ 98%] Built target rsz
[ 98%] Built target cts
[ 98%] Built target rmp
[ 98%] Built target ant_py
[ 98%] Built target gpl_py
[100%] Built target gpl
[100%] Built target cts_py
[100%] Built target rmp_py
[100%] Built target drt_messages
[100%] Built target drt
[100%] Built target drt_py
[100%] Built target ram
[100%] Built target ram_py
[100%] Built target openroad

real	0m2.984s
user	0m8.261s
sys	0m2.852s
[  0%] Built target lefzlib
[  1%] Built target defzlib
[  1%] Built target gui_RUNTIME_HEADER
[  1%] Built target Munkres
[  1%] Built target sta_swig_swig_compilation
[  2%] Built target lef
[  2%] Built target utl_py
[  4%] Built target def
[  4%] Generating messages.checked
[  4%] Built target fft_test
[  4%] Built target utl_lib
[  4%] Generating messages.checked
[  4%] Built target TestMetrics
[  4%] Built target TestAlgorithms
[  4%] Built target TestCFileUtils
[  4%] Built target ppl_messages
[  5%] Built target TestSuppressStdout
[  7%] Built target zutil
[  7%] Built target dst_lib
[  7%] Built target utl_messages
[  7%] Generating messages.checked
[ 13%] Built target OpenSTA
[ 13%] Generating messages.checked
[ 13%] Built target utl
[ 14%] Built target sta_swig
[ 14%] Built target sta
[ 14%] Built target dst_messages
[ 14%] Built target openroad_messages
[ 14%] Built target dst
[ 14%] Built target TestBalancer
[ 16%] Built target TestDistributed
[ 16%] Built target TestWorker
[ 65%] Built target libabc
[ 65%] Built target abc
[ 73%] Built target db
[ 73%] Built target gdsout
[ 73%] Built target lefout
[ 73%] Built target cdl
[ 73%] Built target defout
[ 73%] Built target gdsin
[ 73%] Built target 3dblox
[ 73%] Built target defin
[ 74%] Built target lefin
[ 74%] Generating messages.checked
[ 74%] Built target odb_swig_common
[ 74%] Built target odb_messages
[ 74%] Built target gui_autogen_timestamp_deps
[ 74%] Built target exa_lib
[ 74%] Built target odb_py
[ 76%] Built target odbtcl
[ 76%] Built target stt_lib
[ 76%] Built target ant_lib
[ 76%] Built target dft_config_lib
[ 76%] Built target odb_py-bin
[ 76%] Built target dbSta_lib
[ 76%] Built target dft_utils_scan_pin_lib
[ 76%] Built target odbtcl-bin
[ 76%] Generating messages.checked
[ 76%] Generating messages.checked
[ 76%] Generating messages.checked
[ 76%] Built target tap
[ 76%] Built target dft_clock_domain_lib
[ 76%] Built target stt_messages
[ 76%] Built target gui_autogen
[ 76%] Built target ant_messages
[ 76%] Generating messages.checked
[ 76%] Built target exa_messages
[ 76%] Built target dft_base_scan_cell_lib
[ 76%] Built target dft_clock_domain_hash_lib
[ 77%] Built target rcx_lib
[ 77%] Built target CUGR
[ 79%] Built target par_lib
[ 79%] Built target rcxUnitTest
[ 79%] Built target tap_py
[ 79%] Generating messages.checked
[ 79%] Built target dbSta_messages
[ 79%] Built target par_py
[ 79%] Built target rcx_py
[ 79%] Built target par
[ 79%] Built target dft_architect_lib
[ 79%] Built target TestScanArchitect
[ 79%] Built target dbSta
[ 79%] Built target TestScanArchitectHeuristic
[ 79%] Built target ord
[ 79%] Built target upf_lib
[ 79%] Built target dft_utils_lib
[ 79%] Built target mpl_lib
[ 79%] Built target rcx_messages
[ 80%] Built target upf
[ 80%] Built target dft_cells_lib
[ 80%] Built target rcx
[ 80%] Built target dft_replace_lib
[ 80%] Built target ifp
[ 80%] Built target dft_stitch_lib
[ 80%] Built target ord_py
[ 80%] Built target ifp_py
[ 80%] Generating messages.checked
[ 80%] Built target dpl_lib
[ 80%] Built target dft_messages
[ 80%] Generating messages.checked
[ 80%] Built target dft
[ 80%] Built target est_lib
[ 80%] Built target dft_py
[ 80%] Built target dpl_messages
[ 82%] Built target gui
[ 82%] Built target FastRoute4.1
[ 82%] Built target exa_py
[ 83%] Built target stt
[ 83%] Built target exa
[ 83%] Built target fin
[ 83%] Built target mpl
[ 85%] Built target dpl_py
[ 86%] Built target dpl
[ 86%] Built target ppl
[ 86%] Built target fin_py
[ 86%] Built target stt_py
[ 86%] Built target ppl_py
[ 86%] Built target pad
[ 86%] Built target grt_lib
[ 86%] Built target pdn
[ 88%] Built target pdn_py
[ 88%] Built target rsz_lib
[ 89%] Generating messages.checked
[ 89%] Generating messages.checked
[ 89%] Generating messages.checked
[ 92%] Built target drt_lib
[ 92%] Built target est_messages
[ 92%] Built target ant
[ 92%] Built target rsz_messages
[ 92%] Built target grt_messages
[ 92%] Built target cut
[ 92%] Generating messages.checked
[ 92%] Built target gpl_lib
[ 92%] Built target cts_lib
[ 92%] Built target grt_py
[ 92%] Built target tst
[ 92%] Generating messages.checked
[ 92%] Built target est
[ 92%] Built target psm
[ 92%] Built target trTest
[ 92%] Built target TestSnapper
[ 92%] Built target cts_unittest
[ 92%] Built target cgt
[ 92%] Built target grt
[ 92%] Built target cts_messages
[ 94%] Built target psm_py
[ 94%] Built target CutGTests
[ 94%] Built target odb_test_helper
[ 94%] Built target TestHconn
[ 94%] Built target drt_messages
[ 95%] Built target rmp_lib
[ 95%] Built target TestDbSta
[ 95%] Built target TestBufRem1
[ 95%] Built target TestReadVerilog
[ 95%] Built target TestBufferRemoval2
[ 95%] Built target TestInsertBuffer
[ 95%] Built target TestBufferRemoval3
[ 95%] Built target mbff_test
[ 97%] Built target cgt_py
[ 97%] Built target dpl_test
[ 97%] Built target RmpGTests
[ 97%] Built target TestCallBacks
[ 98%] Built target TestGeom
[ 98%] Built target OdbGTests
[ 98%] Built target rmp
[ 98%] Built target rsz
[ 98%] Built target TestModule
[ 98%] Built target cts
[ 98%] Built target TestLef58Properties
[ 98%] Built target TestGroup
[ 98%] Built target TestGCellGrid
[ 98%] Built target TestJournal
[ 98%] Built target TestAccessPoint
[ 98%] Built target TestGuide
[ 98%] Built target TestNetTrack
[ 98%] Built target TestMaster
[ 98%] Built target TestGDSIn
[ 98%] Built target drt
[ 98%] Built target TestChips
[ 98%] Built target Test3DBloxParser
[ 98%] Built target TestSwapMaster
[ 98%] Built target TestSwapMasterUnusedPort
[ 98%] Built target Test3DBloxChecker
[ 98%] Built target TestObjectType
[ 98%] Built target TestScanChain
[ 98%] Built target gpl_py
[100%] Built target gpl
[100%] Built target drt_py
[100%] Built target ant_py
[100%] Built target TestWriteReadDbHier
[100%] Built target rmp_py
[100%] Built target cts_py
[100%] Built target ram
[100%] Built target ram_py
[100%] Built target openroad
Install the project...
-- Install configuration: "RELEASE"
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/bin/sta
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/lib/libOpenSTA.a
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/CycleAccting.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/EnumNameMap.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/SdcCmdComment.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/WriteSdc.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Sta.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/TableModel.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/VerilogWriter.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/ContainerHelpers.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Transition.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Stats.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/StaMain.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/StringSeq.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/PatternMatch.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/DelayFloat.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/PathExpanded.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Mode.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/ClkNetwork.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/TimingArc.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/DataCheck.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/SearchClass.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/CircuitSim.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/SdcClass.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/GraphCmp.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/ObjectTable.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/PowerClass.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/RiseFallMinMaxDelay.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Search.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/GraphDelayCalc.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/DisabledPorts.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/TimingModel.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/StringUtil.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Property.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/SdcNetwork.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Units.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/TclTypeHelpers.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/VertexId.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/VerilogNamespace.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Bdd.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Hash.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Debug.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/DelayNormal2.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/ConcreteLibrary.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/LeakagePower.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Parasitics.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Error.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/StaState.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/PinPair.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/ParseBus.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/TimingRole.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/ReportTcl.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Sdc.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/ParasiticsClass.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/MakeConcreteNetwork.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/VectorMap.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Variables.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/ClockLatency.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/DelayNormal1.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/InputDrive.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/PathEnd.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/NetworkCmp.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/ClockGatingCheck.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/NetworkClass.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/PortDirection.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/RiseFallValues.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Mutex.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Clock.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/DelayCalc.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/DispatchQueue.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Scene.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Sequential.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Liberty.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/ArcDelayCalc.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Fuzzy.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/BoundedHeap.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Report.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/LibertyWriter.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/InternalPower.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/StringSet.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/VertexVisitor.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/DeratingFactors.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/PortExtCap.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Wireload.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/ExceptionPath.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/TokenParser.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/FuncExpr.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/SearchPred.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Bfs.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/MinMax.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/ReportStd.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/VerilogReader.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/ConcreteNetwork.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/PathGroup.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Iterator.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/PortDelay.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Graph.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/HpinDrvrLoad.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/MinMaxValues.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/ClockGroups.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/RiseFallMinMax.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Delay.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/LibertyClass.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Machine.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Network.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/ClockInsertion.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/LinearModel.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/GraphClass.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/VisitPathEnds.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/ObjectId.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/EquivCells.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Path.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/Zlib.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/include/sta/StaConfig.hh
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/share/openroad/gui/icon.png
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/share/applications/openroad.desktop
-- Up-to-date: /home/themi/OpenROAD-flow-scripts/tools/install/OpenROAD/bin/openroad
[INFO FLW-0017] Compiling Yosys.
make: Entering directory '/home/themi/OpenROAD-flow-scripts/tools/yosys'
mkdir -p /home/themi/OpenROAD-flow-scripts/tools/install/yosys/bin
cp yosys-abc yosys yosys-config yosys-filterlib yosys-smtbmc yosys-witness /home/themi/OpenROAD-flow-scripts/tools/install/yosys/bin
if [ -n "strip" ]; then  strip -S /home/themi/OpenROAD-flow-scripts/tools/install/yosys/bin/yosys; fi
if [ -n "strip" ]; then  strip /home/themi/OpenROAD-flow-scripts/tools/install/yosys/bin/yosys-abc; fi
if [ -n "strip" ]; then  strip /home/themi/OpenROAD-flow-scripts/tools/install/yosys/bin/yosys-filterlib; fi
mkdir -p /home/themi/OpenROAD-flow-scripts/tools/install/yosys/share/yosys
cp -r share/. /home/themi/OpenROAD-flow-scripts/tools/install/yosys/share/yosys/.
make: Leaving directory '/home/themi/OpenROAD-flow-scripts/tools/yosys'
[INFO FLW-0030] Compiling yosys-slang.
make: Entering directory '/home/themi/OpenROAD-flow-scripts/tools/yosys-slang'
cmake -S . -B build -DYOSYS_CONFIG=/home/themi/OpenROAD-flow-scripts/tools/install/yosys/bin/yosys-config -DYOSYS_SLANG_REVISION=unknown -DSLANG_REVISION=unknown
-- slang version: 9.1.171+d7888c90a
-- Build STATIC library as: svlang
-- {fmt} version: 11.2.1
-- Build type: 
-- Using remote fmt library
-- Found system boost 1.89.0 at /home/themi/OpenROAD-flow-scripts/dependencies/include
-- Using yosys: /home/themi/OpenROAD-flow-scripts/tools/install/yosys/bin/yosys-config
-- yosys-config --bindir: /home/themi/OpenROAD-flow-scripts/tools/install/yosys/bin
-- yosys-config --datdir: /home/themi/OpenROAD-flow-scripts/tools/install/yosys/share/yosys
-- yosys-config --cxxflags (filtered): -I/home/themi/OpenROAD-flow-scripts/tools/install/yosys/share/yosys/include;-D_YOSYS_;-I/home/themi/OpenROAD-flow-scripts/tools/install/yosys/include;-DYOSYS_VER="0.63";-DYOSYS_MAJOR=0;-DYOSYS_MINOR=63;-DYOSYS_COMMIT=0.63;-DYOSYS_ENABLE_READLINE;-DYOSYS_ENABLE_PLUGINS;-DYOSYS_ENABLE_GLOB;-DYOSYS_ENABLE_ZLIB;-I/usr/include/tcl8.6;-DYOSYS_ENABLE_TCL;-DYOSYS_ENABLE_THREADS;-DYOSYS_ENABLE_ABC
-- Got YOSYS_SLANG_REVISION: unknown
-- Got SLANG_REVISION: unknown
-- Configuring done (0.2s)
-- Generating done (0.0s)
-- Build files have been written to: /home/themi/OpenROAD-flow-scripts/tools/yosys-slang/build
cmake --build build
gmake[1]: Entering directory '/home/themi/OpenROAD-flow-scripts/tools/yosys-slang/build'
gmake[2]: Entering directory '/home/themi/OpenROAD-flow-scripts/tools/yosys-slang/build'
gmake[3]: Entering directory '/home/themi/OpenROAD-flow-scripts/tools/yosys-slang/build'
gmake[3]: Leaving directory '/home/themi/OpenROAD-flow-scripts/tools/yosys-slang/build'
[  2%] Built target fmt
gmake[3]: Entering directory '/home/themi/OpenROAD-flow-scripts/tools/yosys-slang/build'
gmake[3]: Leaving directory '/home/themi/OpenROAD-flow-scripts/tools/yosys-slang/build'
[ 91%] Built target slang_slang
gmake[3]: Entering directory '/home/themi/OpenROAD-flow-scripts/tools/yosys-slang/build'
gmake[3]: Leaving directory '/home/themi/OpenROAD-flow-scripts/tools/yosys-slang/build'
gmake[3]: Entering directory '/home/themi/OpenROAD-flow-scripts/tools/yosys-slang/build'
[ 91%] Building CXX object src/CMakeFiles/yosys-slang.dir/abort_helpers.cc.o
[ 92%] Building CXX object src/CMakeFiles/yosys-slang.dir/addressing.cc.o
[ 93%] Building CXX object src/CMakeFiles/yosys-slang.dir/async_pattern.cc.o
[ 93%] Building CXX object src/CMakeFiles/yosys-slang.dir/blackboxes.cc.o
[ 94%] Building CXX object src/CMakeFiles/yosys-slang.dir/builder.cc.o
[ 95%] Building CXX object src/CMakeFiles/yosys-slang.dir/cases.cc.o
[ 95%] Building CXX object src/CMakeFiles/yosys-slang.dir/diag.cc.o
[ 96%] Building CXX object src/CMakeFiles/yosys-slang.dir/naming.cc.o
[ 96%] Building CXX object src/CMakeFiles/yosys-slang.dir/procedural.cc.o
[ 97%] Building CXX object src/CMakeFiles/yosys-slang.dir/slang_frontend.cc.o
[ 98%] Building CXX object src/CMakeFiles/yosys-slang.dir/variables.cc.o
[ 99%] Linking CXX shared library ../slang.so
gmake[3]: Leaving directory '/home/themi/OpenROAD-flow-scripts/tools/yosys-slang/build'
[100%] Built target yosys-slang
gmake[2]: Leaving directory '/home/themi/OpenROAD-flow-scripts/tools/yosys-slang/build'
gmake[1]: Leaving directory '/home/themi/OpenROAD-flow-scripts/tools/yosys-slang/build'
cmake --install build
-- Install configuration: ""
-- Installing: /home/themi/OpenROAD-flow-scripts/tools/install/yosys/share/yosys/plugins/slang.so
make: Leaving directory '/home/themi/OpenROAD-flow-scripts/tools/yosys-slang'
[INFO FLW-0031] Compiling kepler-formal
-- CMake version: 3.31.9
-- CMake version: 3.31.9
CMake Error at thirdparty/naja/CMakeLists.txt:102 (find_package):
  By not providing "FindTBB.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "TBB", but
  CMake did not find one.

  Could not find a package configuration file provided by "TBB" with any of
  the following names:

    TBBConfig.cmake
    tbb-config.cmake

  Add the installation prefix of "TBB" to CMAKE_PREFIX_PATH or set "TBB_DIR"
  to a directory containing one of the above files.  If "TBB" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
```

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by LucasYuki**
Closes #3968.

Changes:
- Kepler dependencies moved from `_installCI` to `_installUbuntuPackages`.

### CODE REVIEW

File: etc/DependencyInstaller.sh [hunk 1]
```diff
@@ -152,19 +152,29 @@ _installUbuntuPackages() {
...
+        libfmt-dev \
         libfl2 \
         libgit2-dev \
         libgoogle-perftools-dev \
+        libgtest-dev \
         libqt5multimediawidgets5 \
         libqt5opengl5 \
         libqt5svg5-dev \
         libqt5xmlpatterns5-dev \
+        libspdlog-dev \
```
Comment (maliberty) [inline etc/DependencyInstaller.sh]: We have _install_spdlog - do we need this too?

File: etc/DependencyInstaller.sh [hunk 2]
```diff
@@ -152,19 +152,29 @@ _installUbuntuPackages() {
...
+        capnproto \
+        clang \
         curl \
         flex \
         help2man \
+        libboost-dev \
+        libboost-iostreams-dev \
+        libcapnp-dev \
         libfl-dev \
+        libfmt-dev \
```
Comment (maliberty) [inline etc/DependencyInstaller.sh]: same _install_spdlog

File: etc/DependencyInstaller.sh [hunk 3]
```diff
@@ -152,19 +152,29 @@ _installUbuntuPackages() {
     apt-get -y update
     apt-get -y install --no-install-recommends \
         bison \
+        capnproto \
+        clang \
         curl \
         flex \
         help2man \
+        libboost-dev \
+        libboost-iostreams-dev \
```
Comment (maliberty) [inline etc/DependencyInstaller.sh]: same _install_boost

File: etc/DependencyInstaller.sh [hunk 4]
```diff
@@ -152,19 +152,29 @@ _installUbuntuPackages() {
     apt-get -y update
     apt-get -y install --no-install-recommends \
         bison \
+        capnproto \
+        clang \
```
Comment (maliberty) [inline etc/DependencyInstaller.sh]: already in _install_ubuntu_packages

Comment (LucasYuki) [reply etc/DependencyInstaller.sh]: Both of them or only clang?

Comment (maliberty) [reply etc/DependencyInstaller.sh]: clang

File: etc/DependencyInstaller.sh (hunk 1 above)
Comment (LucasYuki) [reply etc/DependencyInstaller.sh]: removed

File: etc/DependencyInstaller.sh (hunk 2 above)
Comment (LucasYuki) [reply etc/DependencyInstaller.sh]: removed

File: etc/DependencyInstaller.sh (hunk 3 above)
Comment (LucasYuki) [reply etc/DependencyInstaller.sh]: libboost-dev was removed, but libboost-iostreams-dev is necessary.

File: etc/DependencyInstaller.sh (hunk 4 above)
Comment (LucasYuki) [reply etc/DependencyInstaller.sh]: removed

**Review by maliberty — APPROVED** [review]
